# Generated by Django 3.2.3 on 2021-09-04 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', '0004_place_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placeusername', to=settings.AUTH_USER_MODEL),
        ),
    ]
