# Generated by Django 3.2.3 on 2021-10-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_alter_place_author'),
        ('accounts', '0003_auto_20211005_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='places',
            field=models.ManyToManyField(to='weather.Place'),
        ),
    ]
